apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: NodePort
  selector:
    app: flask-wine-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080  # Optional: exposed port on your host

x